### ISSUE TITLE
Decompile exe file

### ISSUE THREAD

**Issue by ap-apely** [B64-Cryptzo/Scudo#1]
Using your code, I encrypted the functions using std:unique_ptrScudonewFunction(new Scudo(&Add));. But after decompiling my exe by using hydra, I can get the source code of the functions in unencrypted form. It turns out that protection is only against copying from memory or am I mistaken, thank you in advance

**Comment by B64-Cryptzo** [comment]
The aim and use case of this library is to encrypt functions being used while the program is running. This method prevents code pattern scans and binary dumping.

Decompiling the static library will yeild unencrypted function however if the executeable is packed or dumped at runtime to be analysed by IDA or Ghidra, it will be encrypted due to the runtime initialization of the classe.

**Comment by ap-apely** [comment]
> The aim and use case of this library is to encrypt functions being used while the program is running. This method prevents code pattern scans and binary dumping.
> 
> Decompiling the static library will yeild unencrypted function however if the executeable is packed or dumped at runtime to be analysed by IDA or Ghidra, it will be encrypted due to the runtime initialization of the classe.

Thank you very much for your answer and code. If it’s not difficult for you, how is it possible or what can be used to encrypt the function and other variables to protect against static analysis

**Comment by B64-Cryptzo** [comment]
I suggest you look into packers and obfuscators. Static analysis often is used to get an idea of how a program works. When you pack an exe, the program must be run for its content to accessible in a decompiler. Using this at runtime paired with a packer would accomplish what you are attempting to do.
